"""Declarative navigation contracts for the CPU-owned REZO-family UIs.

These values are shared by firmware, the control peripherals, renderers, and
display tests.  They intentionally contain no encoder state machine or
persistence implementation; production navigation and state ownership live in
firmware.
"""


class RezoUISpec:
    TARGET_PAGE = 0
    TARGET_PRESET = 1
    TARGET_BAND_BASE = 2
    TARGET_DRIVE = 12
    TARGET_RESONANCE = 13
    TARGET_FEEDBACK = 14
    TARGET_LIMIT_KNEE = 15
    TARGET_LIMIT_CAP = 16
    TARGET_DAMP = 17
    TARGET_INPUT_BASE = 18
    TARGET_GROUP_BASE = 30
    TARGET_OUTPUT_BASE = 40
    TARGET_MODE = 60
    TARGET_FILTER_TYPE = 61
    TARGET_FILTER_CUTOFF = 62
    TARGET_FILTER_SLOPE = 63
    TARGET_FILTER_WIDTH = 64
    TARGET_FILTER_CV_BASE = 65
    TARGET_FEEDBACK_SEND_BASE = 80
    TARGET_PALETTE = 90
    TARGET_SAVE_DEFAULT = 91
    TARGET_BAND_LAYOUT = 92
    TARGET_BAND_ENABLE_BASE = 93
    TARGET_BAND_FREQ_BASE = 103
    TARGET_OUTPUT_ROW_BASE = 113
    TARGET_OUTPUT_COL_BASE = 117
    TARGET_OUTPUT_DRY_COL = 121
    N_TARGETS = 122


class RezomoUISpec:
    TARGET_PAGE = 0
    TARGET_PRESET = 1
    TARGET_BAND_BASE = 2
    TARGET_DRIVE = 12
    TARGET_RESONANCE = 13
    TARGET_FEEDBACK = 14
    TARGET_LIMIT_KNEE = 15
    TARGET_LIMIT_CAP = 16
    TARGET_DAMP = 17
    TARGET_INPUT_BASE = 18
    TARGET_GROUP_BASE = 30
    TARGET_OUTPUT_BASE = 40
    TARGET_MODE = 60
    TARGET_SHIFT_DIRECTION = 61
    TARGET_CLOCK_ALGORITHM = 62
    TARGET_TURING_LENGTH = 63
    TARGET_TURING_CHANGE = 64
    TARGET_CLOCK_SOURCE = 65
    TARGET_CLOCK_RATE = 66
    TARGET_CLOCK_DEPTH = 67
    TARGET_TURING_TARGET = 68
    TARGET_TURING_START = 69
    TARGET_DATA_SOURCE = 70
    TARGET_WALK_STYLE = TARGET_TURING_TARGET
    TARGET_WALK_DRUNK = TARGET_TURING_LENGTH
    TARGET_WALK_CHANCE = TARGET_TURING_CHANGE
    TARGET_FEEDBACK_SEND_BASE = 80
    TARGET_PALETTE = 90
    TARGET_SAVE_DEFAULT = 91
    TARGET_BAND_LAYOUT = 92
    TARGET_BAND_ENABLE_BASE = 93
    TARGET_BAND_FREQ_BASE = 103
    TARGET_OUTPUT_ROW_BASE = 113
    TARGET_OUTPUT_COL_BASE = 117
    TARGET_OUTPUT_DRY_COL = 121
    N_TARGETS = 122


class StrezoUISpec:
    TARGET_PAGE = 0
    TARGET_PRESET = 1
    TARGET_BAND_BASE = 2
    TARGET_DRIVE = 12
    TARGET_RESONANCE = 13
    TARGET_FEEDBACK = 14
    TARGET_LIMIT_KNEE = 15
    TARGET_LIMIT_CAP = 16
    TARGET_DAMP = 17
    TARGET_INPUT_BASE = 18
    TARGET_GROUP_BASE = 30
    TARGET_OUTPUT_BASE = 40
    TARGET_CROSS_LAYOUT = 60
    TARGET_MOTION_SOURCE = 61
    TARGET_MOTION_RATE = 62
    TARGET_MOTION_PHASE = 63
    TARGET_MOTION_DEPTH = TARGET_PRESET
    TARGET_CROSS_MATRIX_BASE = 64
    TARGET_FEEDBACK_SEND_BASE = 80
    TARGET_PALETTE = 90
    TARGET_SAVE_DEFAULT = 91
    TARGET_BAND_LAYOUT = 92
    TARGET_BAND_ENABLE_BASE = 93
    TARGET_BAND_FREQ_BASE = 103
    TARGET_CROSS_FEEDBACK = 113
    TARGET_OUTPUT_SIDE_BASE = 114
    TARGET_CROSS_ROW_BASE = 118
    TARGET_CROSS_COL_BASE = 122
    TARGET_OUTPUT_ROW_BASE = TARGET_CROSS_ROW_BASE
    TARGET_OUTPUT_COL_BASE = TARGET_CROSS_COL_BASE
    TARGET_OUTPUT_DRY_COL = TARGET_CROSS_LAYOUT
    TARGET_SAME_FEEDBACK = 126
    TARGET_CROSS_CURVE = TARGET_MOTION_DEPTH
    # OUTPUT and CROSS are disjoint pages, so the two page-local faders can
    # reuse the otherwise exhausted seven-bit target space.
    TARGET_MID_GAIN = TARGET_SAME_FEEDBACK
    TARGET_SIDE_GAIN = TARGET_CROSS_FEEDBACK
    N_TARGETS = 127
