# SPDX-License-Identifier: MIT OR Apache-2.0
"""Compact capitals from embedded-graphics FONT_7X13/FONT_7X13_BOLD.

Source: embedded-graphics a293ee30, fonts/raw/ascii/font_7x13{,_bold}.raw.
Keep exact rows 1..10 in a 7x10 cell. Capital ink is nine rows high, hence
18 pixels at 2x. Lowercase aliases capitals to preserve descenders as labels.
No interpolation or bitmap resampling is used.
"""
from base64 import b64decode

_NORMAL = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgoAAIgAgIQAAAAAACACChQRSACBAgAAAAAAIAIKFDyRgIECEggAAABAAgA+UCJAAgEMCAAAAEACABQ4IkACAT8+APgAgAIAPhRBgAIBDAgAAAEAAgAUeJJQAQISCAAAAQAAABQRKiABAgAAOABCAAIAAAER0ACEAAAwAOIAAAAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCHn4J+OfnjwAABAEDxIYhAhkBAChQgAAIAIQoSiEEKQIASFCECBAARChCAQhJcgCIUY4cIfggKEICHImK4IeOhAhAABBIQgwCiAsRCECAACAAIIhCEAL8ChEIQIAAEfhAhIIgQgkKEghBBBwIAIADD788CPHiB44OGAQBAIAAAAAAAAAAAAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4Y+PPn788hPh0KBChPISRFCRQIEKEICRIGaFChQkUBFAgQIQgJIgZsUKdCRQEUCBAhCAlCBapQqUJ5ARePED8ICYIFqVCrfkUBFAgToQgJQgQo0KVCRQEUCBChCAkiBChQoEJFCRQIEaEIiRIEKFCeQvjz5+gOoT5xC/QoTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwA8AAPjz48fQoUKEi/IEAQQAhQoUIRChQoSIEgQBCgCFChQBEKFCSFAiAgERAIUKFAEQkkJIUEICAQAA+QvjwRCSWjAgwgEBAACBCoAhEJJaSCCCAIEAAIFKQCEQjGZIIQIAgQAAgSokIRCMZoQiAgBBAACA8hPBDwxChCPyAEEAAAAIAAAAAAAAAAPADwB+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAEAIAAEAOAIAABAMAAAAAAgAAQBEAgCAUAQAAAAACAABAEACAAAQBAAAAAPLjx08QOrhgNEENLjwACxQo0LxExCAUgQqxQgD6FAhfkESEIBcBCqFCAQoUCFAQOIQgFIEKoUIBGxQo0JBAhCAUQQqhQgDq48dPEDyE+RQnyKE8AAAAAAAAQgABEAAAAAAAAAAAAAA8AADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAOAAAAAAAAAAAAAAABAQEJPAAAAAQAAAAAAAEBARVCAAAABAAAAAAAAQEBEkK46uPPEJEihQvwgQIAAsUZFCQQkSJJCCMBAYAEhQkDBBCRKjEIQIECAAjFGQDEEIoqMRiBAQEACLjpBCRRiipI6QEBAQAAgAkDw46EFIQL8QEBAAiACAAAAAAAAQgA4A4AAIAIAAAAAAAA8AAAAAAA"
_BOLD = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhsUMcnBgYwAAAAAAGAGGxR5W2GDBgAAAAAAYAYbPrXTYYMGEhgAAADABgA+sDNhhgMMGAAAAMAGABR4YcAGAz9+AAABgAYAPjTDUAYDP34B+AMAAAA+tLtwAwYMGDgAAwAGABR5q2ADBhIYOADGAAYAFDE50AGMAAAwAeYAAAAAAAAAAAAAAGAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMGHn4N+efnjwAADAMDxI4zBh2DMGzZgAAYAYZs1jMMPYMAbNmMGDAAxmzGAxht8wDM2Z48YfhgbMYOPM2b4MePjBjAADHMxhgGzBsxjMGAAGAAYYzGMAb8GzGMwYAcMfjABIYwZg2bMwzZjBwYAYGDH788DPHjB48eGAwDAYAAAAAAAAAAAAwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB48+PPn788zfg2LBCzPI2bNmzYMGbMYDZsGbNmjZs2DNgwYMxgNswfu2a9mzYM2DBgzGA3jB+7Zq375gzfPm78YDcMGb9mvZs2DNgwZsxgN4wZt2aBmzYM2DBmzGA2zBm3Zo2bNmzYMGbMYzZsGbNmeZvjz5+wPs355i/ZszwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPjz48/Zs2aFm/PMDwwAzZs2YxmzZs2YMwwDHgDNmzYDGbNmSPAzBgMzAM2bNgMZkmZ48GMGAyEA+ZvjwxmSZjBgwwMDAADBm8BjGZ5+eGGDAYMAAMHbYGMZjH5IYwMBgwAAwbs2YxmMZsxjAwDDAADA8xPDDwxChGPzwM8AfgAYAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAMAMAAMAOAMBgNgcAAAAYAwAAwBsAwGA2AwAAAAADAADAGADAAAYDAAAAAPPjx88YOvjgNmMbPjwAGzZs2bxmzGA2wx+zZgD7NgzfmGbMYDeDH7NmAZs2DNgYPMxgN4MZs2YBmzZs2ZhgzGA2wxmzZgD748fPGDzN+DZv2bM8AAAAAAAAZgADMAAAAAAAAAAAAAA8AAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABww4ZPAAAAAYAAAAAAAMDAz9mAAAABgAAAAAAAwMDJmb4++PPmbNmzZvxgwYABs2bNmYZs2bNmDMDAwAczZsDBhmzZnmYYYMGABjNmwDGGZ5+eZmDAwMAAPj7BmbZnn7M+wMDAwAYwBsDw4+MJMwb8cMOABjAGAAAAAAAAZgAAAAAAMAYAAAAAAAA8AAAAAAA"


def _rows(encoded):
    raw = b64decode(encoded)
    result = []
    for code in range(32, 127):
        char = chr(code)
        source = char.upper() if char.isascii() and char.islower() else char
        glyph = ord(source) - 32
        for y in range(1, 11):
            value = 0
            for x in range(7):
                bit = (glyph // 16 * 13 + y) * 112 + glyph % 16 * 7 + x
                value = (value << 1) | ((raw[bit // 8] >> (7 - bit % 8)) & 1)
            if char == "_" and y == 10:
                value = 0x7e
            result.append(value)
    return result


UX_FONT_NORMAL = _rows(_NORMAL)
UX_FONT_BOLD = _rows(_BOLD)
