"""Generate bounded, allocation-free firmware help from reviewed Markdown."""
import json
import textwrap
from pathlib import Path

COLUMNS = 36
VISIBLE_ROWS = 9
TOPICS = ('START', 'TUNER', 'CAL', 'CAL PROFILES', 'SCALES', 'SCALE TOOLS',
          'ROUTES', 'MIDI TRANSPOSE', 'CONFIGS', 'OPTIONS')
ROOT = Path(__file__).parent


def render():
    source = (ROOT / 'INTONO_HELP.md').read_text()
    body = source.split('<!-- HELP START -->', 1)[1].split('<!-- HELP END -->', 1)[0]
    sections = body.strip().split('## ')[1:]
    assert tuple(s.split('\n', 1)[0] for s in sections) == TOPICS
    result = '// Generated by help_content.py; edit INTONO_HELP.md.\n'
    result += 'pub static TOPICS: [(&str, &str); 10] = [\n'
    total = 0
    for name, section in zip(TOPICS, sections):
        prose = section.split('\n', 1)[1].strip()
        assert prose.isascii(), 'Use display-compatible ASCII prose'
        paragraphs = ['\n'.join(textwrap.wrap(p, COLUMNS, break_long_words=False,
                      break_on_hyphens=False)) for p in prose.split('\n\n')]
        wrapped = '\n\n'.join(paragraphs)
        lines = wrapped.splitlines()
        assert all(len(line) <= COLUMNS for line in lines)
        assert len(lines) - VISIBLE_ROWS <= 60, 'Exceeds SCROLL range'
        total += len(wrapped)
        result += f'    ({json.dumps(name)}, {json.dumps(wrapped)}),\n'
    assert total <= 10000, 'Help exceeds firmware text budget'
    return result + '];\n'


if __name__ == '__main__':
    (ROOT / 'fw/src/help_text.rs').write_text(render())
