"""Generate bounded, allocation-free firmware help from reviewed Markdown."""
import json
from collections import Counter
import textwrap
from pathlib import Path

COLUMNS = 36
VISIBLE_ROWS = 9
TOPICS = ('START', 'TUNER', 'CAL', 'CAL PROFILES', 'SCALES', 'SCALE TOOLS',
          'ROUTES', 'MIDI TRANSPOSE', 'CONFIGS', 'OPTIONS')
ROOT = Path(__file__).parent


def render():
    source = (ROOT / 'INTONO_HELP.md').read_text()
    body = source.split('<!-- HELP START -->', 1)[1].split('<!-- HELP END -->', 1)[0]
    sections = body.strip().split('## ')[1:]
    assert tuple(s.split('\n', 1)[0] for s in sections) == TOPICS
    result = '// Generated by help_content.py; edit INTONO_HELP.md.\n'
    topics = []
    total = 0
    for name, section in zip(TOPICS, sections):
        prose = section.split('\n', 1)[1].strip()
        assert prose.isascii(), 'Use display-compatible ASCII prose'
        paragraphs = ['\n'.join(textwrap.wrap(p, COLUMNS, break_long_words=False,
                      break_on_hyphens=False)) for p in prose.split('\n\n')]
        wrapped = '\n\n'.join(paragraphs)
        lines = wrapped.splitlines()
        assert all(len(line) <= COLUMNS for line in lines)
        assert len(lines) - VISIBLE_ROWS <= 120, 'Exceeds SCROLL range'
        total += len(wrapped)
        topics.append((name, wrapped))
    assert total <= 10000, 'Help exceeds firmware text budget'
    # ASCII text remains the source of truth. Frequent literal phrases use
    # otherwise-unused bytes, with a packed dictionary and no recursive tokens.
    codes = [*range(128, 256), *range(1, 10), *range(11, 32), 127]
    parts = [body.encode() for _, body in topics]
    phrases = []
    for code in codes:
        counts = Counter()
        for part in parts:
            for size in range(3, 33):
                counts.update(part[n:n+size] for n in range(len(part)-size+1)
                              if all(v == 10 or 32 <= v < 127 for v in part[n:n+size]))
        phrase, score = max(((p, (len(p)-1)*n-len(p)-2) for p, n in counts.items()),
                            key=lambda item: item[1])
        if score <= 0: break
        parts = [part.replace(phrase, bytes([code])) for part in parts]
        phrases.append(phrase)
    offsets = [0]
    for phrase in phrases: offsets.append(offsets[-1] + len(phrase))
    def literal(data):
        return 'b"' + ''.join(chr(v) if 32 <= v < 127 and v not in (34, 92)
                             else f"\\x{v:02x}" for v in data) + '"'
    result += 'pub static DICTIONARY: &[u8] = ' + literal(b''.join(phrases)) + ';\n'
    result += 'pub static OFFSETS: &[u16] = &[' + ','.join(map(str, offsets)) + '];\n'
    result += 'pub static TOPICS: [(&str, &[u8], u8); 10] = [\n'
    for (name, body), part in zip(topics, parts):
        result += f'    ({json.dumps(name)}, {literal(part)}, {len(body.splitlines())}),\n'
    result += '];\n#[cfg(test)] pub static RAW: [&str; 10] = [\n'
    result += ''.join(json.dumps(body) + ',\n' for _, body in topics)
    return result + '];\n'



if __name__ == '__main__':
    (ROOT / 'fw/src/help_text.rs').write_text(render())
