[package]
name = "rezo-hybrid-probe-fw"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "=0.11.1"
riscv-rt = { version = "=0.12.2", features = ["single-hart"] }
panic-halt = "0.2.0"

[profile.release]
codegen-units = 1
debug = true
debug-assertions = false
incremental = false
lto = true
opt-level = 2
overflow-checks = false
