[target.riscv32im-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tintono-cache-memory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tintono-runtime.x",
]

[build]
target = "riscv32im-unknown-none-elf"
